/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as loggedInRouteRouteImport } from './routes/(logged-in)/route'
import { Route as layoutRouteRouteImport } from './routes/(layout)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgsOrgSlugRouteRouteImport } from './routes/orgs/$orgSlug/route'
import { Route as loggedInAccountRouteRouteImport } from './routes/(logged-in)/account/route'
import { Route as layoutDocsRouteRouteImport } from './routes/(layout)/docs/route'
import { Route as OrgsNewIndexRouteImport } from './routes/orgs/new/index'
import { Route as OrgsListIndexRouteImport } from './routes/orgs/list/index'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthNewUserIndexRouteImport } from './routes/auth/new-user/index'
import { Route as AuthGoodbyeIndexRouteImport } from './routes/auth/goodbye/index'
import { Route as AuthForgetPasswordIndexRouteImport } from './routes/auth/forget-password/index'
import { Route as AuthConfirmDeleteIndexRouteImport } from './routes/auth/confirm-delete/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin/feedback/index'
import { Route as loggedInAccountIndexRouteImport } from './routes/(logged-in)/account/index'
import { Route as layoutPostsIndexRouteImport } from './routes/(layout)/posts/index'
import { Route as layoutDocsIndexRouteImport } from './routes/(layout)/docs/index'
import { Route as layoutContactIndexRouteImport } from './routes/(layout)/contact/index'
import { Route as layoutChangelogIndexRouteImport } from './routes/(layout)/changelog/index'
import { Route as layoutAboutIndexRouteImport } from './routes/(layout)/about/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as layoutDocsSplatRouteImport } from './routes/(layout)/docs/$'
import { Route as OrgsOrgSlugnavigationRouteRouteImport } from './routes/orgs/$orgSlug/(navigation)/route'
import { Route as OrgsAcceptInvitationIdIndexRouteImport } from './routes/orgs/accept-invitation/$id/index'
import { Route as OrgsOrgSlugnavigationIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/index'
import { Route as AuthSigninOtpIndexRouteImport } from './routes/auth/signin/otp/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminOrganizationsOrgIdIndexRouteImport } from './routes/admin/organizations/$orgId/index'
import { Route as AdminFeedbackFeedbackIdIndexRouteImport } from './routes/admin/feedback/$feedbackId/index'
import { Route as loggedInAccountSecurityIndexRouteImport } from './routes/(logged-in)/account/security/index'
import { Route as loggedInAccountDangerIndexRouteImport } from './routes/(logged-in)/account/danger/index'
import { Route as loggedInAccountChangePasswordIndexRouteImport } from './routes/(logged-in)/account/change-password/index'
import { Route as loggedInAccountChangeEmailIndexRouteImport } from './routes/(logged-in)/account/change-email/index'
import { Route as layoutPostsSlugIndexRouteImport } from './routes/(layout)/posts/$slug/index'
import { Route as layoutPaymentSuccessIndexRouteImport } from './routes/(layout)/payment/success/index'
import { Route as layoutPaymentCancelIndexRouteImport } from './routes/(layout)/payment/cancel/index'
import { Route as layoutLegalTermsIndexRouteImport } from './routes/(layout)/legal/terms/index'
import { Route as layoutLegalPrivacyIndexRouteImport } from './routes/(layout)/legal/privacy/index'
import { Route as layoutChangelogSlugIndexRouteImport } from './routes/(layout)/changelog/$slug/index'
import { Route as OrgsOrgSlugnavigationSettingsRouteRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/route'
import { Route as OrgsOrgSlugnavigationSettingsIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/index'
import { Route as OrgsOrgSlugnavigationDemoIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/demo/index'
import { Route as loggedInAccountSecurityNewPasswordIndexRouteImport } from './routes/(logged-in)/account/security/new-password/index'
import { Route as layoutPostsCategoriesCategoryIndexRouteImport } from './routes/(layout)/posts/categories/$category/index'
import { Route as ApiAdminOrganizationsOrgIdPaymentsRouteImport } from './routes/api/admin/organizations/$orgId/payments'
import { Route as OrgsOrgSlugnavigationSettingsMembersIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/members/index'
import { Route as OrgsOrgSlugnavigationSettingsDangerIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/danger/index'
import { Route as OrgsOrgSlugnavigationSettingsApiKeysIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/api-keys/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/route'
import { Route as OrgsOrgSlugnavigationSettingsBillingSuccessIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/success/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingCancelIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/cancel/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingtabsIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/usage/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/plan/index'
import { Route as OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRouteImport } from './routes/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/payment/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const loggedInRouteRoute = loggedInRouteRouteImport.update({
  id: '/(logged-in)',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgsOrgSlugRouteRoute = OrgsOrgSlugRouteRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const loggedInAccountRouteRoute = loggedInAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => loggedInRouteRoute,
} as any)
const layoutDocsRouteRoute = layoutDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => layoutRouteRoute,
} as any)
const OrgsNewIndexRoute = OrgsNewIndexRouteImport.update({
  id: '/orgs/new/',
  path: '/orgs/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsListIndexRoute = OrgsListIndexRouteImport.update({
  id: '/orgs/list/',
  path: '/orgs/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewUserIndexRoute = AuthNewUserIndexRouteImport.update({
  id: '/new-user/',
  path: '/new-user/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGoodbyeIndexRoute = AuthGoodbyeIndexRouteImport.update({
  id: '/goodbye/',
  path: '/goodbye/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetPasswordIndexRoute = AuthForgetPasswordIndexRouteImport.update({
  id: '/forget-password/',
  path: '/forget-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthConfirmDeleteIndexRoute = AuthConfirmDeleteIndexRouteImport.update({
  id: '/confirm-delete/',
  path: '/confirm-delete/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const loggedInAccountIndexRoute = loggedInAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => loggedInAccountRouteRoute,
} as any)
const layoutPostsIndexRoute = layoutPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutDocsIndexRoute = layoutDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutDocsRouteRoute,
} as any)
const layoutContactIndexRoute = layoutContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutChangelogIndexRoute = layoutChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutAboutIndexRoute = layoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutDocsSplatRoute = layoutDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => layoutDocsRouteRoute,
} as any)
const OrgsOrgSlugnavigationRouteRoute =
  OrgsOrgSlugnavigationRouteRouteImport.update({
    id: '/(navigation)',
    getParentRoute: () => OrgsOrgSlugRouteRoute,
  } as any)
const OrgsAcceptInvitationIdIndexRoute =
  OrgsAcceptInvitationIdIndexRouteImport.update({
    id: '/orgs/accept-invitation/$id/',
    path: '/orgs/accept-invitation/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgSlugnavigationIndexRoute =
  OrgsOrgSlugnavigationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const AuthSigninOtpIndexRoute = AuthSigninOtpIndexRouteImport.update({
  id: '/signin/otp/',
  path: '/signin/otp/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsOrgIdIndexRoute =
  AdminOrganizationsOrgIdIndexRouteImport.update({
    id: '/organizations/$orgId/',
    path: '/organizations/$orgId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminFeedbackFeedbackIdIndexRoute =
  AdminFeedbackFeedbackIdIndexRouteImport.update({
    id: '/feedback/$feedbackId/',
    path: '/feedback/$feedbackId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const loggedInAccountSecurityIndexRoute =
  loggedInAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountDangerIndexRoute =
  loggedInAccountDangerIndexRouteImport.update({
    id: '/danger/',
    path: '/danger/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountChangePasswordIndexRoute =
  loggedInAccountChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const loggedInAccountChangeEmailIndexRoute =
  loggedInAccountChangeEmailIndexRouteImport.update({
    id: '/change-email/',
    path: '/change-email/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const layoutPostsSlugIndexRoute = layoutPostsSlugIndexRouteImport.update({
  id: '/posts/$slug/',
  path: '/posts/$slug/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutPaymentSuccessIndexRoute =
  layoutPaymentSuccessIndexRouteImport.update({
    id: '/payment/success/',
    path: '/payment/success/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutPaymentCancelIndexRoute =
  layoutPaymentCancelIndexRouteImport.update({
    id: '/payment/cancel/',
    path: '/payment/cancel/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutLegalTermsIndexRoute = layoutLegalTermsIndexRouteImport.update({
  id: '/legal/terms/',
  path: '/legal/terms/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutLegalPrivacyIndexRoute = layoutLegalPrivacyIndexRouteImport.update({
  id: '/legal/privacy/',
  path: '/legal/privacy/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutChangelogSlugIndexRoute =
  layoutChangelogSlugIndexRouteImport.update({
    id: '/changelog/$slug/',
    path: '/changelog/$slug/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsRouteRoute =
  OrgsOrgSlugnavigationSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsIndexRoute =
  OrgsOrgSlugnavigationSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationDemoIndexRoute =
  OrgsOrgSlugnavigationDemoIndexRouteImport.update({
    id: '/demo/',
    path: '/demo/',
    getParentRoute: () => OrgsOrgSlugnavigationRouteRoute,
  } as any)
const loggedInAccountSecurityNewPasswordIndexRoute =
  loggedInAccountSecurityNewPasswordIndexRouteImport.update({
    id: '/security/new-password/',
    path: '/security/new-password/',
    getParentRoute: () => loggedInAccountRouteRoute,
  } as any)
const layoutPostsCategoriesCategoryIndexRoute =
  layoutPostsCategoriesCategoryIndexRouteImport.update({
    id: '/posts/categories/$category/',
    path: '/posts/categories/$category/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const ApiAdminOrganizationsOrgIdPaymentsRoute =
  ApiAdminOrganizationsOrgIdPaymentsRouteImport.update({
    id: '/api/admin/organizations/$orgId/payments',
    path: '/api/admin/organizations/$orgId/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgSlugnavigationSettingsMembersIndexRoute =
  OrgsOrgSlugnavigationSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsDangerIndexRoute =
  OrgsOrgSlugnavigationSettingsDangerIndexRouteImport.update({
    id: '/danger/',
    path: '/danger/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsApiKeysIndexRoute =
  OrgsOrgSlugnavigationSettingsApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute =
  OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteImport.update({
    id: '/billing/(tabs)',
    path: '/billing',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingSuccessIndexRouteImport.update({
    id: '/billing/success/',
    path: '/billing/success/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingCancelIndexRouteImport.update({
    id: '/billing/cancel/',
    path: '/billing/cancel/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingtabsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRouteImport.update({
    id: '/usage/',
    path: '/usage/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRouteImport.update({
    id: '/plan/',
    path: '/plan/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute,
  } as any)
const OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute =
  OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs': typeof layoutDocsRouteRouteWithChildren
  '/account': typeof loggedInAccountRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugnavigationRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/docs/$': typeof layoutDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/about/': typeof layoutAboutIndexRoute
  '/changelog/': typeof layoutChangelogIndexRoute
  '/contact/': typeof layoutContactIndexRoute
  '/docs/': typeof layoutDocsIndexRoute
  '/posts/': typeof layoutPostsIndexRoute
  '/account/': typeof loggedInAccountIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/confirm-delete/': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password/': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye/': typeof AuthGoodbyeIndexRoute
  '/auth/new-user/': typeof AuthNewUserIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/orgs/list/': typeof OrgsListIndexRoute
  '/orgs/new/': typeof OrgsNewIndexRoute
  '/orgs/$orgSlug/settings': typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  '/changelog/$slug/': typeof layoutChangelogSlugIndexRoute
  '/legal/privacy/': typeof layoutLegalPrivacyIndexRoute
  '/legal/terms/': typeof layoutLegalTermsIndexRoute
  '/payment/cancel/': typeof layoutPaymentCancelIndexRoute
  '/payment/success/': typeof layoutPaymentSuccessIndexRoute
  '/posts/$slug/': typeof layoutPostsSlugIndexRoute
  '/account/change-email/': typeof loggedInAccountChangeEmailIndexRoute
  '/account/change-password/': typeof loggedInAccountChangePasswordIndexRoute
  '/account/danger/': typeof loggedInAccountDangerIndexRoute
  '/account/security/': typeof loggedInAccountSecurityIndexRoute
  '/admin/feedback/$feedbackId/': typeof AdminFeedbackFeedbackIdIndexRoute
  '/admin/organizations/$orgId/': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/auth/signin/otp/': typeof AuthSigninOtpIndexRoute
  '/orgs/$orgSlug/': typeof OrgsOrgSlugnavigationIndexRoute
  '/orgs/accept-invitation/$id/': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/posts/categories/$category/': typeof layoutPostsCategoriesCategoryIndexRoute
  '/account/security/new-password/': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/demo/': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/settings/': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/settings/billing': typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteWithChildren
  '/orgs/$orgSlug/settings/api-keys/': typeof OrgsOrgSlugnavigationSettingsApiKeysIndexRoute
  '/orgs/$orgSlug/settings/danger/': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/settings/members/': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
  '/orgs/$orgSlug/settings/billing/': typeof OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute
  '/orgs/$orgSlug/settings/billing/cancel/': typeof OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute
  '/orgs/$orgSlug/settings/billing/success/': typeof OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute
  '/orgs/$orgSlug/settings/billing/payment/': typeof OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute
  '/orgs/$orgSlug/settings/billing/plan/': typeof OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute
  '/orgs/$orgSlug/settings/billing/usage/': typeof OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugnavigationIndexRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/docs/$': typeof layoutDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/about': typeof layoutAboutIndexRoute
  '/changelog': typeof layoutChangelogIndexRoute
  '/contact': typeof layoutContactIndexRoute
  '/docs': typeof layoutDocsIndexRoute
  '/posts': typeof layoutPostsIndexRoute
  '/account': typeof loggedInAccountIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/confirm-delete': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye': typeof AuthGoodbyeIndexRoute
  '/auth/new-user': typeof AuthNewUserIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/orgs/list': typeof OrgsListIndexRoute
  '/orgs/new': typeof OrgsNewIndexRoute
  '/changelog/$slug': typeof layoutChangelogSlugIndexRoute
  '/legal/privacy': typeof layoutLegalPrivacyIndexRoute
  '/legal/terms': typeof layoutLegalTermsIndexRoute
  '/payment/cancel': typeof layoutPaymentCancelIndexRoute
  '/payment/success': typeof layoutPaymentSuccessIndexRoute
  '/posts/$slug': typeof layoutPostsSlugIndexRoute
  '/account/change-email': typeof loggedInAccountChangeEmailIndexRoute
  '/account/change-password': typeof loggedInAccountChangePasswordIndexRoute
  '/account/danger': typeof loggedInAccountDangerIndexRoute
  '/account/security': typeof loggedInAccountSecurityIndexRoute
  '/admin/feedback/$feedbackId': typeof AdminFeedbackFeedbackIdIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/auth/signin/otp': typeof AuthSigninOtpIndexRoute
  '/orgs/accept-invitation/$id': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/posts/categories/$category': typeof layoutPostsCategoriesCategoryIndexRoute
  '/account/security/new-password': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/demo': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/settings': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/settings/api-keys': typeof OrgsOrgSlugnavigationSettingsApiKeysIndexRoute
  '/orgs/$orgSlug/settings/danger': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/settings/members': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
  '/orgs/$orgSlug/settings/billing': typeof OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute
  '/orgs/$orgSlug/settings/billing/cancel': typeof OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute
  '/orgs/$orgSlug/settings/billing/success': typeof OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute
  '/orgs/$orgSlug/settings/billing/payment': typeof OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute
  '/orgs/$orgSlug/settings/billing/plan': typeof OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute
  '/orgs/$orgSlug/settings/billing/usage': typeof OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/(logged-in)': typeof loggedInRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og.png': typeof OgDotpngRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(layout)/docs': typeof layoutDocsRouteRouteWithChildren
  '/(logged-in)/account': typeof loggedInAccountRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/orgs/$orgSlug/(navigation)': typeof OrgsOrgSlugnavigationRouteRouteWithChildren
  '/(layout)/docs/$': typeof layoutDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/(layout)/about/': typeof layoutAboutIndexRoute
  '/(layout)/changelog/': typeof layoutChangelogIndexRoute
  '/(layout)/contact/': typeof layoutContactIndexRoute
  '/(layout)/docs/': typeof layoutDocsIndexRoute
  '/(layout)/posts/': typeof layoutPostsIndexRoute
  '/(logged-in)/account/': typeof loggedInAccountIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/confirm-delete/': typeof AuthConfirmDeleteIndexRoute
  '/auth/forget-password/': typeof AuthForgetPasswordIndexRoute
  '/auth/goodbye/': typeof AuthGoodbyeIndexRoute
  '/auth/new-user/': typeof AuthNewUserIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/orgs/list/': typeof OrgsListIndexRoute
  '/orgs/new/': typeof OrgsNewIndexRoute
  '/orgs/$orgSlug/(navigation)/settings': typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  '/(layout)/changelog/$slug/': typeof layoutChangelogSlugIndexRoute
  '/(layout)/legal/privacy/': typeof layoutLegalPrivacyIndexRoute
  '/(layout)/legal/terms/': typeof layoutLegalTermsIndexRoute
  '/(layout)/payment/cancel/': typeof layoutPaymentCancelIndexRoute
  '/(layout)/payment/success/': typeof layoutPaymentSuccessIndexRoute
  '/(layout)/posts/$slug/': typeof layoutPostsSlugIndexRoute
  '/(logged-in)/account/change-email/': typeof loggedInAccountChangeEmailIndexRoute
  '/(logged-in)/account/change-password/': typeof loggedInAccountChangePasswordIndexRoute
  '/(logged-in)/account/danger/': typeof loggedInAccountDangerIndexRoute
  '/(logged-in)/account/security/': typeof loggedInAccountSecurityIndexRoute
  '/admin/feedback/$feedbackId/': typeof AdminFeedbackFeedbackIdIndexRoute
  '/admin/organizations/$orgId/': typeof AdminOrganizationsOrgIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/auth/signin/otp/': typeof AuthSigninOtpIndexRoute
  '/orgs/$orgSlug/(navigation)/': typeof OrgsOrgSlugnavigationIndexRoute
  '/orgs/accept-invitation/$id/': typeof OrgsAcceptInvitationIdIndexRoute
  '/api/admin/organizations/$orgId/payments': typeof ApiAdminOrganizationsOrgIdPaymentsRoute
  '/(layout)/posts/categories/$category/': typeof layoutPostsCategoriesCategoryIndexRoute
  '/(logged-in)/account/security/new-password/': typeof loggedInAccountSecurityNewPasswordIndexRoute
  '/orgs/$orgSlug/(navigation)/demo/': typeof OrgsOrgSlugnavigationDemoIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/': typeof OrgsOrgSlugnavigationSettingsIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)': typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteWithChildren
  '/orgs/$orgSlug/(navigation)/settings/api-keys/': typeof OrgsOrgSlugnavigationSettingsApiKeysIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/danger/': typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/members/': typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/': typeof OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/cancel/': typeof OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/success/': typeof OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/payment/': typeof OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/plan/': typeof OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute
  '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/usage/': typeof OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/feed.xml'
    | '/llms.txt'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/docs'
    | '/account'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home/'
    | '/orgs/'
    | '/docs/$'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/about/'
    | '/changelog/'
    | '/contact/'
    | '/docs/'
    | '/posts/'
    | '/account/'
    | '/admin/feedback/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/auth/confirm-delete/'
    | '/auth/forget-password/'
    | '/auth/goodbye/'
    | '/auth/new-user/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/orgs/list/'
    | '/orgs/new/'
    | '/orgs/$orgSlug/settings'
    | '/changelog/$slug/'
    | '/legal/privacy/'
    | '/legal/terms/'
    | '/payment/cancel/'
    | '/payment/success/'
    | '/posts/$slug/'
    | '/account/change-email/'
    | '/account/change-password/'
    | '/account/danger/'
    | '/account/security/'
    | '/admin/feedback/$feedbackId/'
    | '/admin/organizations/$orgId/'
    | '/admin/users/$userId/'
    | '/auth/signin/otp/'
    | '/orgs/$orgSlug/'
    | '/orgs/accept-invitation/$id/'
    | '/api/admin/organizations/$orgId/payments'
    | '/posts/categories/$category/'
    | '/account/security/new-password/'
    | '/orgs/$orgSlug/demo/'
    | '/orgs/$orgSlug/settings/'
    | '/orgs/$orgSlug/settings/billing'
    | '/orgs/$orgSlug/settings/api-keys/'
    | '/orgs/$orgSlug/settings/danger/'
    | '/orgs/$orgSlug/settings/members/'
    | '/orgs/$orgSlug/settings/billing/'
    | '/orgs/$orgSlug/settings/billing/cancel/'
    | '/orgs/$orgSlug/settings/billing/success/'
    | '/orgs/$orgSlug/settings/billing/payment/'
    | '/orgs/$orgSlug/settings/billing/plan/'
    | '/orgs/$orgSlug/settings/billing/usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed.xml'
    | '/llms.txt'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/orgs/$orgSlug'
    | '/admin'
    | '/home'
    | '/orgs'
    | '/docs/$'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/docs'
    | '/posts'
    | '/account'
    | '/admin/feedback'
    | '/admin/organizations'
    | '/admin/users'
    | '/auth/confirm-delete'
    | '/auth/forget-password'
    | '/auth/goodbye'
    | '/auth/new-user'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify'
    | '/orgs/list'
    | '/orgs/new'
    | '/changelog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/payment/cancel'
    | '/payment/success'
    | '/posts/$slug'
    | '/account/change-email'
    | '/account/change-password'
    | '/account/danger'
    | '/account/security'
    | '/admin/feedback/$feedbackId'
    | '/admin/organizations/$orgId'
    | '/admin/users/$userId'
    | '/auth/signin/otp'
    | '/orgs/accept-invitation/$id'
    | '/api/admin/organizations/$orgId/payments'
    | '/posts/categories/$category'
    | '/account/security/new-password'
    | '/orgs/$orgSlug/demo'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/settings/api-keys'
    | '/orgs/$orgSlug/settings/danger'
    | '/orgs/$orgSlug/settings/members'
    | '/orgs/$orgSlug/settings/billing'
    | '/orgs/$orgSlug/settings/billing/cancel'
    | '/orgs/$orgSlug/settings/billing/success'
    | '/orgs/$orgSlug/settings/billing/payment'
    | '/orgs/$orgSlug/settings/billing/plan'
    | '/orgs/$orgSlug/settings/billing/usage'
  id:
    | '__root__'
    | '/'
    | '/(layout)'
    | '/(logged-in)'
    | '/admin'
    | '/auth'
    | '/feed.xml'
    | '/llms.txt'
    | '/og.png'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(layout)/docs'
    | '/(logged-in)/account'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home/'
    | '/orgs/'
    | '/orgs/$orgSlug/(navigation)'
    | '/(layout)/docs/$'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/(layout)/about/'
    | '/(layout)/changelog/'
    | '/(layout)/contact/'
    | '/(layout)/docs/'
    | '/(layout)/posts/'
    | '/(logged-in)/account/'
    | '/admin/feedback/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/auth/confirm-delete/'
    | '/auth/forget-password/'
    | '/auth/goodbye/'
    | '/auth/new-user/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/orgs/list/'
    | '/orgs/new/'
    | '/orgs/$orgSlug/(navigation)/settings'
    | '/(layout)/changelog/$slug/'
    | '/(layout)/legal/privacy/'
    | '/(layout)/legal/terms/'
    | '/(layout)/payment/cancel/'
    | '/(layout)/payment/success/'
    | '/(layout)/posts/$slug/'
    | '/(logged-in)/account/change-email/'
    | '/(logged-in)/account/change-password/'
    | '/(logged-in)/account/danger/'
    | '/(logged-in)/account/security/'
    | '/admin/feedback/$feedbackId/'
    | '/admin/organizations/$orgId/'
    | '/admin/users/$userId/'
    | '/auth/signin/otp/'
    | '/orgs/$orgSlug/(navigation)/'
    | '/orgs/accept-invitation/$id/'
    | '/api/admin/organizations/$orgId/payments'
    | '/(layout)/posts/categories/$category/'
    | '/(logged-in)/account/security/new-password/'
    | '/orgs/$orgSlug/(navigation)/demo/'
    | '/orgs/$orgSlug/(navigation)/settings/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)'
    | '/orgs/$orgSlug/(navigation)/settings/api-keys/'
    | '/orgs/$orgSlug/(navigation)/settings/danger/'
    | '/orgs/$orgSlug/(navigation)/settings/members/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/cancel/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/success/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/payment/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/plan/'
    | '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
  loggedInRouteRoute: typeof loggedInRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgDotpngRoute: typeof OgDotpngRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OrgsOrgSlugRouteRoute: typeof OrgsOrgSlugRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  OrgsListIndexRoute: typeof OrgsListIndexRoute
  OrgsNewIndexRoute: typeof OrgsNewIndexRoute
  OrgsAcceptInvitationIdIndexRoute: typeof OrgsAcceptInvitationIdIndexRoute
  ApiAdminOrganizationsOrgIdPaymentsRoute: typeof ApiAdminOrganizationsOrgIdPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(logged-in)': {
      id: '/(logged-in)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof loggedInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/orgs/$orgSlug': {
      id: '/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(logged-in)/account': {
      id: '/(logged-in)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof loggedInAccountRouteRouteImport
      parentRoute: typeof loggedInRouteRoute
    }
    '/(layout)/docs': {
      id: '/(layout)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof layoutDocsRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/orgs/new/': {
      id: '/orgs/new/'
      path: '/orgs/new'
      fullPath: '/orgs/new/'
      preLoaderRoute: typeof OrgsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/list/': {
      id: '/orgs/list/'
      path: '/orgs/list'
      fullPath: '/orgs/list/'
      preLoaderRoute: typeof OrgsListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/verify'
      fullPath: '/auth/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/new-user/': {
      id: '/auth/new-user/'
      path: '/new-user'
      fullPath: '/auth/new-user/'
      preLoaderRoute: typeof AuthNewUserIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/goodbye/': {
      id: '/auth/goodbye/'
      path: '/goodbye'
      fullPath: '/auth/goodbye/'
      preLoaderRoute: typeof AuthGoodbyeIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget-password/': {
      id: '/auth/forget-password/'
      path: '/forget-password'
      fullPath: '/auth/forget-password/'
      preLoaderRoute: typeof AuthForgetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/confirm-delete/': {
      id: '/auth/confirm-delete/'
      path: '/confirm-delete'
      fullPath: '/auth/confirm-delete/'
      preLoaderRoute: typeof AuthConfirmDeleteIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(logged-in)/account/': {
      id: '/(logged-in)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof loggedInAccountIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(layout)/posts/': {
      id: '/(layout)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof layoutPostsIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/docs/': {
      id: '/(layout)/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof layoutDocsIndexRouteImport
      parentRoute: typeof layoutDocsRouteRoute
    }
    '/(layout)/contact/': {
      id: '/(layout)/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof layoutContactIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/changelog/': {
      id: '/(layout)/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof layoutChangelogIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/about/': {
      id: '/(layout)/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof layoutAboutIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)/docs/$': {
      id: '/(layout)/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof layoutDocsSplatRouteImport
      parentRoute: typeof layoutDocsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)': {
      id: '/orgs/$orgSlug/(navigation)'
      path: ''
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugnavigationRouteRouteImport
      parentRoute: typeof OrgsOrgSlugRouteRoute
    }
    '/orgs/accept-invitation/$id/': {
      id: '/orgs/accept-invitation/$id/'
      path: '/orgs/accept-invitation/$id'
      fullPath: '/orgs/accept-invitation/$id/'
      preLoaderRoute: typeof OrgsAcceptInvitationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug/(navigation)/': {
      id: '/orgs/$orgSlug/(navigation)/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/auth/signin/otp/': {
      id: '/auth/signin/otp/'
      path: '/signin/otp'
      fullPath: '/auth/signin/otp/'
      preLoaderRoute: typeof AuthSigninOtpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/$orgId/': {
      id: '/admin/organizations/$orgId/'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId/'
      preLoaderRoute: typeof AdminOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback/$feedbackId/': {
      id: '/admin/feedback/$feedbackId/'
      path: '/feedback/$feedbackId'
      fullPath: '/admin/feedback/$feedbackId/'
      preLoaderRoute: typeof AdminFeedbackFeedbackIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(logged-in)/account/security/': {
      id: '/(logged-in)/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof loggedInAccountSecurityIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/danger/': {
      id: '/(logged-in)/account/danger/'
      path: '/danger'
      fullPath: '/account/danger/'
      preLoaderRoute: typeof loggedInAccountDangerIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/change-password/': {
      id: '/(logged-in)/account/change-password/'
      path: '/change-password'
      fullPath: '/account/change-password/'
      preLoaderRoute: typeof loggedInAccountChangePasswordIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(logged-in)/account/change-email/': {
      id: '/(logged-in)/account/change-email/'
      path: '/change-email'
      fullPath: '/account/change-email/'
      preLoaderRoute: typeof loggedInAccountChangeEmailIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(layout)/posts/$slug/': {
      id: '/(layout)/posts/$slug/'
      path: '/posts/$slug'
      fullPath: '/posts/$slug/'
      preLoaderRoute: typeof layoutPostsSlugIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/payment/success/': {
      id: '/(layout)/payment/success/'
      path: '/payment/success'
      fullPath: '/payment/success/'
      preLoaderRoute: typeof layoutPaymentSuccessIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/payment/cancel/': {
      id: '/(layout)/payment/cancel/'
      path: '/payment/cancel'
      fullPath: '/payment/cancel/'
      preLoaderRoute: typeof layoutPaymentCancelIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/legal/terms/': {
      id: '/(layout)/legal/terms/'
      path: '/legal/terms'
      fullPath: '/legal/terms/'
      preLoaderRoute: typeof layoutLegalTermsIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/legal/privacy/': {
      id: '/(layout)/legal/privacy/'
      path: '/legal/privacy'
      fullPath: '/legal/privacy/'
      preLoaderRoute: typeof layoutLegalPrivacyIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/changelog/$slug/': {
      id: '/(layout)/changelog/$slug/'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug/'
      preLoaderRoute: typeof layoutChangelogSlugIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings': {
      id: '/orgs/$orgSlug/(navigation)/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsRouteRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/': {
      id: '/orgs/$orgSlug/(navigation)/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/settings/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/demo/': {
      id: '/orgs/$orgSlug/(navigation)/demo/'
      path: '/demo'
      fullPath: '/orgs/$orgSlug/demo/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationDemoIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationRouteRoute
    }
    '/(logged-in)/account/security/new-password/': {
      id: '/(logged-in)/account/security/new-password/'
      path: '/security/new-password'
      fullPath: '/account/security/new-password/'
      preLoaderRoute: typeof loggedInAccountSecurityNewPasswordIndexRouteImport
      parentRoute: typeof loggedInAccountRouteRoute
    }
    '/(layout)/posts/categories/$category/': {
      id: '/(layout)/posts/categories/$category/'
      path: '/posts/categories/$category'
      fullPath: '/posts/categories/$category/'
      preLoaderRoute: typeof layoutPostsCategoriesCategoryIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/api/admin/organizations/$orgId/payments': {
      id: '/api/admin/organizations/$orgId/payments'
      path: '/api/admin/organizations/$orgId/payments'
      fullPath: '/api/admin/organizations/$orgId/payments'
      preLoaderRoute: typeof ApiAdminOrganizationsOrgIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgSlug/(navigation)/settings/members/': {
      id: '/orgs/$orgSlug/(navigation)/settings/members/'
      path: '/members'
      fullPath: '/orgs/$orgSlug/settings/members/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsMembersIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/danger/': {
      id: '/orgs/$orgSlug/(navigation)/settings/danger/'
      path: '/danger'
      fullPath: '/orgs/$orgSlug/settings/danger/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsDangerIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/api-keys/': {
      id: '/orgs/$orgSlug/(navigation)/settings/api-keys/'
      path: '/api-keys'
      fullPath: '/orgs/$orgSlug/settings/api-keys/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsApiKeysIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)'
      path: '/billing'
      fullPath: '/orgs/$orgSlug/settings/billing'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/success/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/success/'
      path: '/billing/success'
      fullPath: '/orgs/$orgSlug/settings/billing/success/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingSuccessIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/cancel/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/cancel/'
      path: '/billing/cancel'
      fullPath: '/orgs/$orgSlug/settings/billing/cancel/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingCancelIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/'
      path: '/'
      fullPath: '/orgs/$orgSlug/settings/billing/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/usage/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/usage/'
      path: '/usage'
      fullPath: '/orgs/$orgSlug/settings/billing/usage/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/plan/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/plan/'
      path: '/plan'
      fullPath: '/orgs/$orgSlug/settings/billing/plan/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute
    }
    '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/payment/': {
      id: '/orgs/$orgSlug/(navigation)/settings/billing/(tabs)/payment/'
      path: '/payment'
      fullPath: '/orgs/$orgSlug/settings/billing/payment/'
      preLoaderRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRouteImport
      parentRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute
    }
  }
}

interface layoutDocsRouteRouteChildren {
  layoutDocsSplatRoute: typeof layoutDocsSplatRoute
  layoutDocsIndexRoute: typeof layoutDocsIndexRoute
}

const layoutDocsRouteRouteChildren: layoutDocsRouteRouteChildren = {
  layoutDocsSplatRoute: layoutDocsSplatRoute,
  layoutDocsIndexRoute: layoutDocsIndexRoute,
}

const layoutDocsRouteRouteWithChildren = layoutDocsRouteRoute._addFileChildren(
  layoutDocsRouteRouteChildren,
)

interface layoutRouteRouteChildren {
  layoutDocsRouteRoute: typeof layoutDocsRouteRouteWithChildren
  layoutAboutIndexRoute: typeof layoutAboutIndexRoute
  layoutChangelogIndexRoute: typeof layoutChangelogIndexRoute
  layoutContactIndexRoute: typeof layoutContactIndexRoute
  layoutPostsIndexRoute: typeof layoutPostsIndexRoute
  layoutChangelogSlugIndexRoute: typeof layoutChangelogSlugIndexRoute
  layoutLegalPrivacyIndexRoute: typeof layoutLegalPrivacyIndexRoute
  layoutLegalTermsIndexRoute: typeof layoutLegalTermsIndexRoute
  layoutPaymentCancelIndexRoute: typeof layoutPaymentCancelIndexRoute
  layoutPaymentSuccessIndexRoute: typeof layoutPaymentSuccessIndexRoute
  layoutPostsSlugIndexRoute: typeof layoutPostsSlugIndexRoute
  layoutPostsCategoriesCategoryIndexRoute: typeof layoutPostsCategoriesCategoryIndexRoute
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layoutDocsRouteRoute: layoutDocsRouteRouteWithChildren,
  layoutAboutIndexRoute: layoutAboutIndexRoute,
  layoutChangelogIndexRoute: layoutChangelogIndexRoute,
  layoutContactIndexRoute: layoutContactIndexRoute,
  layoutPostsIndexRoute: layoutPostsIndexRoute,
  layoutChangelogSlugIndexRoute: layoutChangelogSlugIndexRoute,
  layoutLegalPrivacyIndexRoute: layoutLegalPrivacyIndexRoute,
  layoutLegalTermsIndexRoute: layoutLegalTermsIndexRoute,
  layoutPaymentCancelIndexRoute: layoutPaymentCancelIndexRoute,
  layoutPaymentSuccessIndexRoute: layoutPaymentSuccessIndexRoute,
  layoutPostsSlugIndexRoute: layoutPostsSlugIndexRoute,
  layoutPostsCategoriesCategoryIndexRoute:
    layoutPostsCategoriesCategoryIndexRoute,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

interface loggedInAccountRouteRouteChildren {
  loggedInAccountIndexRoute: typeof loggedInAccountIndexRoute
  loggedInAccountChangeEmailIndexRoute: typeof loggedInAccountChangeEmailIndexRoute
  loggedInAccountChangePasswordIndexRoute: typeof loggedInAccountChangePasswordIndexRoute
  loggedInAccountDangerIndexRoute: typeof loggedInAccountDangerIndexRoute
  loggedInAccountSecurityIndexRoute: typeof loggedInAccountSecurityIndexRoute
  loggedInAccountSecurityNewPasswordIndexRoute: typeof loggedInAccountSecurityNewPasswordIndexRoute
}

const loggedInAccountRouteRouteChildren: loggedInAccountRouteRouteChildren = {
  loggedInAccountIndexRoute: loggedInAccountIndexRoute,
  loggedInAccountChangeEmailIndexRoute: loggedInAccountChangeEmailIndexRoute,
  loggedInAccountChangePasswordIndexRoute:
    loggedInAccountChangePasswordIndexRoute,
  loggedInAccountDangerIndexRoute: loggedInAccountDangerIndexRoute,
  loggedInAccountSecurityIndexRoute: loggedInAccountSecurityIndexRoute,
  loggedInAccountSecurityNewPasswordIndexRoute:
    loggedInAccountSecurityNewPasswordIndexRoute,
}

const loggedInAccountRouteRouteWithChildren =
  loggedInAccountRouteRoute._addFileChildren(loggedInAccountRouteRouteChildren)

interface loggedInRouteRouteChildren {
  loggedInAccountRouteRoute: typeof loggedInAccountRouteRouteWithChildren
}

const loggedInRouteRouteChildren: loggedInRouteRouteChildren = {
  loggedInAccountRouteRoute: loggedInAccountRouteRouteWithChildren,
}

const loggedInRouteRouteWithChildren = loggedInRouteRoute._addFileChildren(
  loggedInRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminFeedbackFeedbackIdIndexRoute: typeof AdminFeedbackFeedbackIdIndexRoute
  AdminOrganizationsOrgIdIndexRoute: typeof AdminOrganizationsOrgIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminFeedbackFeedbackIdIndexRoute: AdminFeedbackFeedbackIdIndexRoute,
  AdminOrganizationsOrgIdIndexRoute: AdminOrganizationsOrgIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthConfirmDeleteIndexRoute: typeof AuthConfirmDeleteIndexRoute
  AuthForgetPasswordIndexRoute: typeof AuthForgetPasswordIndexRoute
  AuthGoodbyeIndexRoute: typeof AuthGoodbyeIndexRoute
  AuthNewUserIndexRoute: typeof AuthNewUserIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
  AuthSigninOtpIndexRoute: typeof AuthSigninOtpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthConfirmDeleteIndexRoute: AuthConfirmDeleteIndexRoute,
  AuthForgetPasswordIndexRoute: AuthForgetPasswordIndexRoute,
  AuthGoodbyeIndexRoute: AuthGoodbyeIndexRoute,
  AuthNewUserIndexRoute: AuthNewUserIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
  AuthSigninOtpIndexRoute: AuthSigninOtpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteChildren {
  OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute
  OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute
  OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute
  OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute
}

const OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteChildren: OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteChildren =
  {
    OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingtabsIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingtabsPaymentIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingtabsPlanIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingtabsUsageIndexRoute,
  }

const OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteWithChildren =
  OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute._addFileChildren(
    OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteChildren,
  )

interface OrgsOrgSlugnavigationSettingsRouteRouteChildren {
  OrgsOrgSlugnavigationSettingsIndexRoute: typeof OrgsOrgSlugnavigationSettingsIndexRoute
  OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute: typeof OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteWithChildren
  OrgsOrgSlugnavigationSettingsApiKeysIndexRoute: typeof OrgsOrgSlugnavigationSettingsApiKeysIndexRoute
  OrgsOrgSlugnavigationSettingsDangerIndexRoute: typeof OrgsOrgSlugnavigationSettingsDangerIndexRoute
  OrgsOrgSlugnavigationSettingsMembersIndexRoute: typeof OrgsOrgSlugnavigationSettingsMembersIndexRoute
  OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute
  OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute: typeof OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute
}

const OrgsOrgSlugnavigationSettingsRouteRouteChildren: OrgsOrgSlugnavigationSettingsRouteRouteChildren =
  {
    OrgsOrgSlugnavigationSettingsIndexRoute:
      OrgsOrgSlugnavigationSettingsIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingtabsRouteRoute:
      OrgsOrgSlugnavigationSettingsBillingtabsRouteRouteWithChildren,
    OrgsOrgSlugnavigationSettingsApiKeysIndexRoute:
      OrgsOrgSlugnavigationSettingsApiKeysIndexRoute,
    OrgsOrgSlugnavigationSettingsDangerIndexRoute:
      OrgsOrgSlugnavigationSettingsDangerIndexRoute,
    OrgsOrgSlugnavigationSettingsMembersIndexRoute:
      OrgsOrgSlugnavigationSettingsMembersIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingCancelIndexRoute,
    OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute:
      OrgsOrgSlugnavigationSettingsBillingSuccessIndexRoute,
  }

const OrgsOrgSlugnavigationSettingsRouteRouteWithChildren =
  OrgsOrgSlugnavigationSettingsRouteRoute._addFileChildren(
    OrgsOrgSlugnavigationSettingsRouteRouteChildren,
  )

interface OrgsOrgSlugnavigationRouteRouteChildren {
  OrgsOrgSlugnavigationSettingsRouteRoute: typeof OrgsOrgSlugnavigationSettingsRouteRouteWithChildren
  OrgsOrgSlugnavigationIndexRoute: typeof OrgsOrgSlugnavigationIndexRoute
  OrgsOrgSlugnavigationDemoIndexRoute: typeof OrgsOrgSlugnavigationDemoIndexRoute
}

const OrgsOrgSlugnavigationRouteRouteChildren: OrgsOrgSlugnavigationRouteRouteChildren =
  {
    OrgsOrgSlugnavigationSettingsRouteRoute:
      OrgsOrgSlugnavigationSettingsRouteRouteWithChildren,
    OrgsOrgSlugnavigationIndexRoute: OrgsOrgSlugnavigationIndexRoute,
    OrgsOrgSlugnavigationDemoIndexRoute: OrgsOrgSlugnavigationDemoIndexRoute,
  }

const OrgsOrgSlugnavigationRouteRouteWithChildren =
  OrgsOrgSlugnavigationRouteRoute._addFileChildren(
    OrgsOrgSlugnavigationRouteRouteChildren,
  )

interface OrgsOrgSlugRouteRouteChildren {
  OrgsOrgSlugnavigationRouteRoute: typeof OrgsOrgSlugnavigationRouteRouteWithChildren
}

const OrgsOrgSlugRouteRouteChildren: OrgsOrgSlugRouteRouteChildren = {
  OrgsOrgSlugnavigationRouteRoute: OrgsOrgSlugnavigationRouteRouteWithChildren,
}

const OrgsOrgSlugRouteRouteWithChildren =
  OrgsOrgSlugRouteRoute._addFileChildren(OrgsOrgSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  layoutRouteRoute: layoutRouteRouteWithChildren,
  loggedInRouteRoute: loggedInRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgDotpngRoute: OgDotpngRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OrgsOrgSlugRouteRoute: OrgsOrgSlugRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  OrgsListIndexRoute: OrgsListIndexRoute,
  OrgsNewIndexRoute: OrgsNewIndexRoute,
  OrgsAcceptInvitationIdIndexRoute: OrgsAcceptInvitationIdIndexRoute,
  ApiAdminOrganizationsOrgIdPaymentsRoute:
    ApiAdminOrganizationsOrgIdPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
